#!/bin/bash -x

set -e

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

if [ "$OSP_DESKTOP" = "true" ]; then

  #XFCE
  chroot "$TARGET" /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -y -o \
    Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install dbus-x11  2> /dev/null

  chroot "$TARGET" /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -y -o \
    Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install xfce4  2> /dev/null

  chroot "$TARGET" /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -y -o \
    Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install xfce4-terminal  2> /dev/null

  chroot "$TARGET" /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -y -o \
    Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install mousepad  2> /dev/null

  chroot "$TARGET" /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -y -o \
    Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install firefox-esr  2> /dev/null

  chroot "$TARGET" /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -y -o \
    Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install xfce4-goodies  2> /dev/null

  chroot "$TARGET" /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -y -o \
    Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install thunar  2> /dev/null


  #/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml
  mkdir -p $TARGET/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/
  cat >> $TARGET/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<channel name="displays" version="1.0">
<property name="Default" type="empty">
<property name="Virtual-1" type="string" value="Virtual-1">
<property name="Active" type="bool" value="true"/>
<property name="Resolution" type="string" value="1920x1080"/>
<property name="RefreshRate" type="double" value="60.000000"/>
<property name="Rotation" type="int" value="0"/>
<property name="Reflection" type="string" value="0"/>
<property name="Primary" type="bool" value="true"/>
<property name="Position" type="empty">
<property name="X" type="int" value="0"/>
<property name="Y" type="int" value="0"/>
</property>
<property name="EDID" type="string" value="" />
</property>
</property>
</channel>
EOF

  #FOR ROOT
  mkdir -p $TARGET/root/.config/xfce4/xfconf/xfce-perchannel-xml/
  cat >> $TARGET/root/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<channel name="displays" version="1.0">
<property name="Default" type="empty">
<property name="Virtual-1" type="string" value="Virtual-1">
<property name="Active" type="bool" value="true"/>
<property name="Resolution" type="string" value="1920x1080"/>
<property name="RefreshRate" type="double" value="60.000000"/>
<property name="Rotation" type="int" value="0"/>
<property name="Reflection" type="string" value="0"/>
<property name="Primary" type="bool" value="true"/>
<property name="Position" type="empty">
<property name="X" type="int" value="0"/>
<property name="Y" type="int" value="0"/>
</property>
<property name="EDID" type="string" value="" />
</property>
</property>
</channel>
EOF

fi

exit 0
