#!/bin/bash

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

mkdir -p $TARGET/root/.ssh

#NCR Access


#Student Access
if [ $OSP_COURSE = "CS447" ]; then
	echo "$OSP_PUBLICKEY" >> $TARGET/root/.ssh/authorized_keys
fi

echo "Key insertion hook done"

exit 0
