#!/bin/bash

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

if [ "$OSP_CS447" = "true" ]; then

	echo "VM is apart of CS447 exiting display hook"
	exit 0
fi

#/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml
mkdir -p $TARGET/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/
cat >> $TARGET/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<channel name="displays" version="1.0">
<property name="Default" type="empty">
<property name="Virtual-1" type="string" value="Virtual-1">
<property name="Active" type="bool" value="true"/>
<property name="Resolution" type="string" value="1920x1080"/>
<property name="RefreshRate" type="double" value="60.000000"/>
<property name="Rotation" type="int" value="0"/>
<property name="Reflection" type="string" value="0"/>
<property name="Primary" type="bool" value="true"/>
<property name="Position" type="empty">
<property name="X" type="int" value="0"/>
<property name="Y" type="int" value="0"/>
</property>
<property name="EDID" type="string" value="" />
</property>
</property>
</channel>
EOF

#FOR ROOT
mkdir -p $TARGET/root/.config/xfce4/xfconf/xfce-perchannel-xml/
cat >> $TARGET/root/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<channel name="displays" version="1.0">
<property name="Default" type="empty">
<property name="Virtual-1" type="string" value="Virtual-1">
<property name="Active" type="bool" value="true"/>
<property name="Resolution" type="string" value="1920x1080"/>
<property name="RefreshRate" type="double" value="60.000000"/>
<property name="Rotation" type="int" value="0"/>
<property name="Reflection" type="string" value="0"/>
<property name="Primary" type="bool" value="true"/>
<property name="Position" type="empty">
<property name="X" type="int" value="0"/>
<property name="Y" type="int" value="0"/>
</property>
<property name="EDID" type="string" value="" />
</property>
</property>
</channel>
EOF

exit 0
